# Generated by Django 3.1.1 on 2020-10-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
