# Generated by Django 3.1.3 on 2021-08-04 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0003_alter_quote_jobfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('iogv', models.CharField(choices=[('KGA', 'КГА'), ('CIOGD', 'ЦИОГД'), ('NIPC', 'НИПЦ')], max_length=50)),
                ('taxpayer_number', models.IntegerField(blank=True)),
                ('snils_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('work_phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('IAC', 'ИАЦ'), ('KAZN', 'Фед.Казначейство')], max_length=100)),
                ('gis_required', models.CharField(choices=[('1783', 'МАИС ЭГУ(1783)'), ('2693', 'ЕССК(2693)')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Действует'), ('end_out', 'Закончилась')], max_length=20)),
                ('description', models.TextField()),
                ('submitted', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.customer')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
