# Generated by Django 3.1.3 on 2021-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20210804_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='taxpayer_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
