# Generated by Django 3.2.4 on 2021-08-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_customer_iogv'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='iogv',
            field=models.CharField(choices=[('KGA', 'КГА'), ('CIOGD', 'ЦИОГД'), ('NIPC', 'НИПЦ')], default='KGA', max_length=50, verbose_name='IOGV'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='snils_number',
            field=models.CharField(max_length=30, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='taxpayer_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='digitalsign',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.customer', verbose_name='Владелец сертификата'),
        ),
        migrations.RemoveField(
            model_name='digitalsign',
            name='gis_required',
        ),
        migrations.AddField(
            model_name='digitalsign',
            name='gis_required',
            field=models.ManyToManyField(help_text='Выберите одну или несколько ГИС для сертификата', to='quotes.GisNumber'),
        ),
    ]
