# Generated by Django 3.2.4 on 2021-08-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20210810_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='digitalsign',
            options={'ordering': ['end_date']},
        ),
        migrations.RemoveField(
            model_name='digitalsign',
            name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(default=0, max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='iogv',
            field=models.CharField(choices=[('KGA', 'КГА'), ('CIOGD', 'ЦИОГД'), ('NIPC', 'НИПЦ')], default='KGA', max_length=50, verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='work_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='digitalsign',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_sign', to='quotes.customer', verbose_name='Владелец сертификата'),
        ),
        migrations.AlterField(
            model_name='digitalsign',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
