# Generated by Django 3.2.4 on 2021-09-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20210823_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='taxpayer_number',
            field=models.CharField(max_length=50, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='digitalsign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='digitalsign',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='digitalsign',
            name='gis_required',
            field=models.ManyToManyField(help_text='Выберите одну или несколько ГИС для сертификата', to='quotes.GisNumber', verbose_name='Необходимые ГИС'),
        ),
        migrations.AlterField(
            model_name='digitalsign',
            name='sign_type',
            field=models.CharField(choices=[('IAC', 'ИАЦ'), ('KAZN', 'Фед.Казначейство')], max_length=100, verbose_name='Тип подписи'),
        ),
        migrations.AlterField(
            model_name='digitalsign',
            name='start_date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
    ]
